server.port=8443
spring.application.name=laboratorio1

spring.data.mongodb.uri=mongodb://mongo1:27017,mongo2:27017/laboratorio1?replicaSet=rs0&authSource=admin
app.jwt.secret=esta_es_una_clave_muy_secreta_y_larga_para_cumplir_con_los_256_bits

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot